version: '3'
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - '4000:4000'

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - '3000:3000'