version: "3.8"
services:
  frontend:
    container_name: frontend
    build: ./client/
    restart: always
    ports:
      - 8080:80
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./server/
    restart: always
    expose: 
      - 8080