version: '3'
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    image: test-backend:latest
    ports:
      - '4000:4000'

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    image: test-frontend:latest
    ports:
      - '3000:3000'