version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: examplePassword
      MYSQL_USER: test_user
      MYSQL_PASSWORD: examplePassword2
      MYSQL_DATABASE: todoApp
    volumes:
      - ./sql.sql:/docker-entrypoint-initdb.d/vid_challenge.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      MYSQL_ROOT_PASSWORD: examplePassword
    ports:
      - 127.0.0.1:8080:80
    links:
      - db:db
