version: '3.1'

services:

  # https://hub.docker.com/_/mongo
  mongodb:
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: bongo
    volumes:
      - mongodata:/data/db
    networks:
      - mongonet

  # https://hub.docker.com/_/mongo-express
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: bongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:bongo@mongodb:27017/
    networks:
      - mongonet

networks:
  mongonet:

volumes:
  mongodata:
